<a href="https://colab.research.google.com/github/Ameena1BM23CS27/6thSem-ML-Lab/blob/main/Decision_Tree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

In [3]:
# Load iris dataset
iris = pd.read_csv("iris (1).csv")

In [4]:
# Separate features and target
X_iris = iris.iloc[:, :-1]   # all columns except last
y_iris = iris.iloc[:, -1]    # last column (target)

In [5]:
# Split dataset (80% train, 20% test)
X_train_i, X_test_i, y_train_i, y_test_i = train_test_split(
    X_iris, y_iris, test_size=0.2, random_state=42
)


In [6]:
# Create Decision Tree model
dt_iris = DecisionTreeClassifier()

In [7]:
# Train the model
dt_iris.fit(X_train_i, y_train_i)

# Predict on test data
y_pred_i = dt_iris.predict(X_test_i)

# Evaluate model
print("IRIS DATASET RESULTS")
print("Accuracy:", accuracy_score(y_test_i, y_pred_i))
print("Confusion Matrix:\n", confusion_matrix(y_test_i, y_pred_i))


IRIS DATASET RESULTS
Accuracy: 1.0
Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [8]:
# -----------------------------
# 2. Decision Tree for Drug Dataset
# -----------------------------

In [9]:
# Load drug dataset
drug = pd.read_csv("drug.csv")

# Convert categorical features to numeric using one-hot encoding
drug_encoded = pd.get_dummies(drug, drop_first=True)

# Separate features and target
X_drug = drug_encoded.drop("Drug_drugY", axis=1) if "Drug_drugY" in drug_encoded.columns else drug_encoded.iloc[:, :-1]
y_drug = drug.iloc[:, -1]

In [10]:
# Split dataset
X_train_d, X_test_d, y_train_d, y_test_d = train_test_split(
    X_drug, y_drug, test_size=0.2, random_state=42
)

# Create Decision Tree model
dt_drug = DecisionTreeClassifier()

# Train the model
dt_drug.fit(X_train_d, y_train_d)

# Predict on test data
y_pred_d = dt_drug.predict(X_test_d)

# Evaluate model
print("\nDRUG DATASET RESULTS")
print("Accuracy:", accuracy_score(y_test_d, y_pred_d))
print("Confusion Matrix:\n", confusion_matrix(y_test_d, y_pred_d))


DRUG DATASET RESULTS
Accuracy: 1.0
Confusion Matrix:
 [[ 6  0  0  0  0]
 [ 0  3  0  0  0]
 [ 0  0  5  0  0]
 [ 0  0  0 11  0]
 [ 0  0  0  0 15]]


In [11]:
# Import required libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [12]:
# Load dataset
data = pd.read_csv("petrol_consumption.csv")

# Separate features (X) and target variable (y)
# Assuming the last column is Petrol_Consumption
X = data.iloc[:, :-1]
y = data.iloc[:, -1]

# Split dataset into training (80%) and testing (20%)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Create Regression Tree model
regressor = DecisionTreeRegressor()

# Train the model
regressor.fit(X_train, y_train)

# Predict on test data
y_pred = regressor.predict(X_test)

# Calculate evaluation metrics
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

# Display results
print("Regression Tree Results")
print("Mean Absolute Error (MAE):", mae)
print("Mean Squared Error (MSE):", mse)
print("Root Mean Squared Error (RMSE):", rmse)

Regression Tree Results
Mean Absolute Error (MAE): 92.1
Mean Squared Error (MSE): 17198.1
Root Mean Squared Error (RMSE): 131.14152660389462
